// export const ActionTypes = {
//     SET_USERS :"SET_USERS",
//     SELECTED_USER: "SELECTED_USER",
//     REMOVE_SELECTED_USER : "REMOVE_SELECTED_USER",


// }
export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";